import 'dotenv/config';
import path from 'path';
import fs from 'fs/promises';
import { prisma } from '../prisma';
import { compileCorrelationReport } from './correlationEngine';
import { capturePayment, voidPayment } from './paypalService';
import { generateReportCollectionToken } from './authService';
import { sendReportReadyNotification } from './emailService';
import { logActivity } from './activityLogger';
import { withTimeout } from './timeout';

const FRONTEND_URL = process.env.FRONTEND_URL || 'http://localhost:3000';
const isProduction = process.env.NODE_ENV === 'production';

// Overall budget for a single in-band correlation run. Bounded so a hung
// upstream (literature / knowledge-base / PayPal) can never pin a report in
// GENERATING indefinitely.
const GENERATION_TIMEOUT_MS = Number(process.env.REPORT_GENERATION_TIMEOUT_MS || 180_000);
// A GENERATING report older than this is considered orphaned (the generator
// crashed mid-flight) and can be reclaimed by a fresh generator.
const GENERATION_LOCK_STALE_MS = Number(process.env.REPORT_GENERATION_LOCK_STALE_MS || 10 * 60_000);
const PAYPAL_TIMEOUT_MS = Number(process.env.PAYPAL_TIMEOUT_MS || 20_000);

/**
 * Atomically claims the exclusive right to generate a report.
 *
 * Only one generator (in-band approve call, or the background worker) may hold
 * the report in GENERATING at a time — enforced with a compare-and-set UPDATE
 * so concurrent in-band + worker runs cannot double-capture the PayPal
 * authorization. Also reclaims reports left GENERATING by a crashed generator
 * whose lock has gone stale.
 */
async function claimReportForGeneration(reportId: string): Promise<boolean> {
  const claimed = await prisma.qeeqReport.updateMany({
    where: {
      id: reportId,
      status: { in: ['PENDING_ADMIN_APPROVAL', 'PAYMENT_AUTHORISED'] },
    },
    data: { status: 'GENERATING', updatedAt: new Date() },
  });
  if (claimed.count === 1) return true;

  const stale = await prisma.qeeqReport.updateMany({
    where: {
      id: reportId,
      status: 'GENERATING',
      updatedAt: { lt: new Date(Date.now() - GENERATION_LOCK_STALE_MS) },
    },
    data: { updatedAt: new Date() },
  });
  return stale.count === 1;
}

/**
 * Runs the full report-generation pipeline for a background job or an in-band
 * admin-approval call:
 * 1. Re-read the report (it may have changed since enqueue).
 * 2. Atomically claim the GENERATING slot.
 * 3. Run the correlation engine and persist the artifact to the filesystem.
 * 4. Capture the PayPal authorization (hard-fail in production rather than
 *    writing a mock capture id).
 * 5. Mark the report COMPLETED with findings, confidence, capture reference.
 * 6. Email the collection link (best-effort; email failure does not fail
 *    the job).
 *
 * Returns true when this call completed the report; false when the report was
 * already COMPLETED or is being generated by another owner (caller should
 * treat the work as done elsewhere and never double-capture).
 */
export async function processReportGeneration(reportId: string): Promise<boolean> {
  const report = await prisma.qeeqReport.findUnique({ where: { id: reportId } });
  if (!report) throw new Error(`Report ${reportId} not found.`);
  if (report.status === 'COMPLETED' || report.status === 'DOWNLOADED_AND_PURGED') return false;
  if (!report.paypalAuthorizationId && isProduction) {
    throw new Error(`Report ${reportId} has no PayPal authorization to capture.`);
  }

  // Only the claimer proceeds; a concurrent generator (worker or in-band
  // approve) that loses the claim must not touch the report.
  const claimed = await claimReportForGeneration(reportId);
  if (!claimed) return false;

  let captureId: string | undefined;

  try {
    const compiledFindings = await withTimeout(
      compileCorrelationReport(
        report.caseReference,
        report.age ?? undefined,
        report.gender ?? undefined,
        report.handedness ?? undefined,
        report.tovaData as Record<string, unknown> | undefined,
        report.checklistData as Record<string, unknown> | undefined,
        report.reliabilityScore ?? undefined
      ),
      GENERATION_TIMEOUT_MS,
      'Correlation analysis'
    );

    const reportsDir = path.join(process.cwd(), 'uploads', report.caseReference);
    await fs.mkdir(reportsDir, { recursive: true });
    const filePath = path.join(reportsDir, `QEEG_Report_${report.caseReference}.json`);
    await fs.writeFile(filePath, JSON.stringify(compiledFindings, null, 2), 'utf-8');

    // Capture the PayPal authorization. In production a missing/mocked capture
    // is a hard failure that will be retried.
    if (report.paypalAuthorizationId) {
      const cap = await withTimeout(
        capturePayment(report.paypalAuthorizationId, report.feeAmount),
        PAYPAL_TIMEOUT_MS,
        'PayPal capture'
      );
      if (!cap.captureId) {
        throw new Error(`PayPal capture for report ${reportId} returned no capture id.`);
      }
      captureId = cap.captureId;
    } else if (!isProduction) {
      captureId = `CAP-MOCK-${reportId}`;
    }

    const updatedReport = await prisma.qeeqReport.update({
      where: { id: reportId },
      data: {
        status: 'COMPLETED',
        confidenceScore: compiledFindings.confidenceScore,
        findings: JSON.parse(JSON.stringify(compiledFindings)),
        reportSummary: compiledFindings.overallSummary,
        filePaths: [filePath],
        paypalCaptureId: captureId,
        paymentStatus: 'CAPTURED',
      },
    });

    await logActivity({
      reportId,
      caseReference: report.caseReference,
      userId: updatedReport.submittingPractitionerId,
      action: 'REPORT_GENERATED',
      details: { confidence: compiledFindings.confidenceScore, captureId },
      ipAddress: 'worker',
    });

    // Best-effort email notification with a one-time collection link. The
    // report is ALREADY persisted as COMPLETED above, so an SMTP failure or
    // timeout must never roll it back, crash the worker, or block the queue:
    // every send path is wrapped and the outcome is logged, never thrown.
    try {
      const practitioner = await prisma.user.findUnique({
        where: { id: updatedReport.submittingPractitionerId },
        include: { practitionerProfile: true },
      });
      const recipient =
        practitioner?.practitionerProfile?.notificationEmail ||
        practitioner?.practitionerProfile?.practiceEmail ||
        practitioner?.email;
      if (recipient) {
        const collectionToken = generateReportCollectionToken(updatedReport.id);
        const collectionLink = `${FRONTEND_URL}/portal?reportId=${updatedReport.id}&token=${collectionToken}`;
        const email = await sendReportReadyNotification(
          recipient,
          practitioner?.practitionerProfile?.fullName || 'Practitioner',
          updatedReport.caseReference,
          collectionLink
        );

        if (email.success) {
          console.log(
            `[Worker] Report-ready email sent: case=${updatedReport.caseReference} to=${recipient} messageId=${email.messageId || (email.simulated ? 'simulated' : 'unknown')}`
          );
        } else {
          console.error(
            `[Worker] Report-ready email FAILED for case=${updatedReport.caseReference} to=${recipient}: ${email.error || 'unknown SMTP error'}`
          );
        }
      } else {
        console.warn(
          `[Worker] No recipient address found for report ${reportId} (case=${updatedReport.caseReference}); skipping notification email.`
        );
      }
    } catch (e) {
      console.error('Report-ready email notification threw unexpectedly:', e);
    }

    return true;
  } catch (error) {
    if (captureId) {
      // The authorization was captured on PayPal but we failed to persist the
      // COMPLETED row (e.g. DB hiccup). Persist the outcome so the practitioner
      // is not double-charged on retry.
      console.error(
        `[Worker] Capture succeeded but COMPLETED persistence failed for report ${reportId}; repairing.`,
        error instanceof Error ? error.message : error
      );
      try {
        await prisma.qeeqReport.update({
          where: { id: reportId },
          data: { status: 'COMPLETED', paypalCaptureId: captureId, paymentStatus: 'CAPTURED' },
        });
      } catch (repairError) {
        console.error(`[Worker] Failed to repair COMPLETED row for report ${reportId}:`, repairError);
      }
    } else {
      // Never leave a report pinned in GENERATING. Roll back to
      // PAYMENT_AUTHORISED: auto-approved cases are re-claimed and
      // re-processed automatically (worker retry or the generate endpoint)
      // without admin intervention, and the rollback target is claimable by
      // the same processor. Only reset if we still own GENERATING.
      await prisma.qeeqReport.updateMany({
        where: { id: reportId, status: 'GENERATING' },
        data: { status: 'PAYMENT_AUTHORISED', updatedAt: new Date() },
      });
    }
    throw error;
  }
}

/**
 * Voids a PayPal authorization for a declined/rejected report. The report row
 * itself (status + paymentStatus) is updated to VOIDED by the decline endpoint
 * so the admin UI responds immediately; this call performs the actual PayPal
 * void and must NOT skip on the VOIDED flag (that flag reflects intent, not
 * completion — skipping would leave the authorization hold in place forever).
 */
export async function processReportVoid(reportId: string): Promise<void> {
  const report = await prisma.qeeqReport.findUnique({ where: { id: reportId } });
  if (!report) throw new Error(`Report ${reportId} not found.`);
  if (!report.paypalAuthorizationId) return;

  const ok = await voidPayment(report.paypalAuthorizationId);
  if (!ok) {
    if (isProduction) throw new Error(`PayPal void for report ${reportId} failed.`);
    return; // dev: void is best-effort
  }
}

export { isProduction };