import 'dotenv/config';
import path from 'path';
import fs from 'fs/promises';
import { prisma } from '../prisma';
import { compileCorrelationReport } from './correlationEngine';
import { voidPayment } from './paypalService';
import { getPaymentProgress } from './installmentPayment';
import { generateReportCollectionToken } from './authService';
import { sendReportReadyNotification } from './emailService';
import { logActivity } from './activityLogger';
import { withTimeout } from './timeout';
import { getPublicUrl } from '../config/publicUrl';

const isProduction = process.env.NODE_ENV === 'production';

// Overall budget for a single in-band correlation run. Bounded so a hung
// upstream (literature / knowledge-base) can never pin a report in
// GENERATING indefinitely.
const GENERATION_TIMEOUT_MS = Number(process.env.REPORT_GENERATION_TIMEOUT_MS || 180_000);
// A GENERATING report older than this is considered orphaned (the generator
// crashed mid-flight) and can be reclaimed by a fresh generator.
const GENERATION_LOCK_STALE_MS = Number(process.env.REPORT_GENERATION_LOCK_STALE_MS || 10 * 60_000);

/**
 * Atomically claims the exclusive right to generate a report.
 *
 * Only one generator (in-band approve call, or the background worker) may hold
 * the report in GENERATING at a time — enforced with a compare-and-set UPDATE
 * so concurrent in-band + worker runs cannot double-capture the PayPal
 * authorization. Also reclaims reports left GENERATING by a crashed generator
 * whose lock has gone stale.
 */
async function claimReportForGeneration(reportId: string): Promise<boolean> {
  const claimed = await prisma.qeeqReport.updateMany({
    where: {
      id: reportId,
      status: { in: ['PENDING_ADMIN_APPROVAL', 'PAYMENT_AUTHORISED'] },
    },
    data: { status: 'GENERATING', updatedAt: new Date() },
  });
  if (claimed.count === 1) return true;

  const stale = await prisma.qeeqReport.updateMany({
    where: {
      id: reportId,
      status: 'GENERATING',
      updatedAt: { lt: new Date(Date.now() - GENERATION_LOCK_STALE_MS) },
    },
    data: { updatedAt: new Date() },
  });
  return stale.count === 1;
}

/**
 * Runs the report-generation step for a background job or an in-band call:
 * 1. Re-read the report (it may have changed since enqueue).
 * 2. Verify the report is fully paid (generation is on HOLD while cumulative
 *    paidAmount < feeAmount in production) and atomically claim GENERATING.
 * 3. Run the correlation engine and persist the artifact to the filesystem.
 * 4. Mark the report COMPLETED with findings + confidence.
 * 5. Email the collection link (best-effort; email failure does not fail
 *    the job).
 *
 * Money is ALWAYS captured earlier, per installment, by capturePaymentInstallment
 * at payment time - NEVER inside this generator. Refunds on terminal failure are
 * the worker's responsibility (refundReportPayments); a plain failure here rolls
 * the report back to PAYMENT_AUTHORISED for an idempotent, safe retry.
 *
 * Returns true when this call completed the report; false when the report was
 * already COMPLETED or is being generated by another owner (caller should treat
 * the work as done elsewhere).
 */
export async function processReportGeneration(reportId: string): Promise<boolean> {
  const report = await prisma.qeeqReport.findUnique({ where: { id: reportId } });
  if (!report) throw new Error(`Report ${reportId} not found.`);
  if (report.status === 'COMPLETED' || report.status === 'DOWNLOADED_AND_PURGED') return false;

  const progress = await getPaymentProgress(report);
  if (isProduction && !progress.fullyPaid) {
    throw new Error(
      `Report ${reportId} has ${progress.remainingAmount.toFixed(2)} AUD outstanding (${progress.paidAmount.toFixed(2)} of ${progress.feeAmount.toFixed(2)} AUD paid). Generation is on HOLD until the full fee is paid.`
    );
  }

  // Only the claimer proceeds; a concurrent generator (worker or in-band
  // approval) that loses the claim must not touch the report.
  const claimed = await claimReportForGeneration(reportId);
  if (!claimed) return false;

  try {

    // Step 1 - correlation + artefact persistence. Reached only once the report
    // is fully paid (captured per-installment at payment time), so it is always
    // paid for by the time it exists on disk.
    const compiledFindings = await withTimeout(
      compileCorrelationReport(
        report.caseReference,
        report.age ?? undefined,
        report.gender ?? undefined,
        report.handedness ?? undefined,
        report.tovaData as Record<string, unknown> | undefined,
        report.checklistData as Record<string, unknown> | undefined,
        report.reliabilityScore ?? undefined
      ),
      GENERATION_TIMEOUT_MS,
      'Correlation analysis'
    );

    const reportsDir = path.join(process.cwd(), 'uploads', report.caseReference);
    await fs.mkdir(reportsDir, { recursive: true });
    const filePath = path.join(reportsDir, `QEEG_Report_${report.caseReference}.json`);
    await fs.writeFile(filePath, JSON.stringify(compiledFindings, null, 2), 'utf-8');

    // Step 2 - mark COMPLETED with findings, confidence, report summary. Capture
    // references were already recorded by capturePaymentInstallment at payment
    // time (per-installment entries live in paymentsJson), so nothing
    // money-related is touched here.
    const updatedReport = await prisma.qeeqReport.update({
      where: { id: reportId },
      data: {
        status: 'COMPLETED',
        confidenceScore: compiledFindings.confidenceScore,
        findings: JSON.parse(JSON.stringify(compiledFindings)),
        reportSummary: compiledFindings.overallSummary,
        filePaths: [filePath],
      },
    });

    await logActivity({
      reportId,
      caseReference: report.caseReference,
      userId: updatedReport.submittingPractitionerId,
      action: 'REPORT_GENERATED',
      details: { confidence: compiledFindings.confidenceScore, paidAmount: progress.paidAmount },
      ipAddress: 'worker',
    });

    // Best-effort email notification with a one-time collection link. The
    // report is ALREADY persisted as COMPLETED above, so an SMTP failure or
    // timeout must never roll it back, crash the worker, or block the queue:
    // every send path is wrapped and the outcome is logged, never thrown.
    try {
      const practitioner = await prisma.user.findUnique({
        where: { id: updatedReport.submittingPractitionerId },
        include: { practitionerProfile: true },
      });
      const recipient =
        practitioner?.practitionerProfile?.notificationEmail ||
        practitioner?.practitionerProfile?.practiceEmail ||
        practitioner?.email;
      if (recipient) {
        const collectionToken = generateReportCollectionToken(updatedReport.id);
        // Public HTTPS domain, not the CORS origin: this one-time signed
        // collection link is emailed to the practitioner, so it must not
        // inherit a localhost / VPS :3000 origin.
        const collectionLink = getPublicUrl(
          `/portal?reportId=${updatedReport.id}&token=${collectionToken}`
        );
        const email = await sendReportReadyNotification(
          recipient,
          practitioner?.practitionerProfile?.fullName || 'Practitioner',
          updatedReport.caseReference,
          collectionLink
        );

        if (email.success) {
          console.log(
            `[Worker] Report-ready email sent: case=${updatedReport.caseReference} to=${recipient} messageId=${email.messageId || (email.simulated ? 'simulated' : 'unknown')}`
          );
        } else {
          console.error(
            `[Worker] Report-ready email FAILED for case=${updatedReport.caseReference} to=${recipient}: ${email.error || 'unknown SMTP error'}`
          );
        }
      } else {
        console.warn(
          `[Worker] No recipient address found for report ${reportId} (case=${updatedReport.caseReference}); skipping notification email.`
        );
      }
    } catch (e) {
      console.error('Report-ready email notification threw unexpectedly:', e);
    }

    return true;
  } catch (error) {
    // This generator owns GENERATING: any failure (correlation timeout,
    // compile/persistence error) rolls the report back to PAYMENT_AUTHORISED so
    // the worker retry or the generate endpoint can re-claim and re-run it. The
    // installments already captured are untouched - refunds on terminal failure
    // are the worker's job (refundReportPayments), never this generator's. Only
    // reset if we still own GENERATING so we never stomp a concurrent claim.
    await prisma.qeeqReport.updateMany({
      where: { id: reportId, status: 'GENERATING' },
      data: { status: 'PAYMENT_AUTHORISED', updatedAt: new Date() },
    });
    throw error;
  }
}

/**
 * Voids a PayPal authorization for a declined/rejected report. The report row
 * itself (status + paymentStatus) is updated to VOIDED by the decline endpoint
 * so the admin UI responds immediately; this call performs the actual PayPal
 * void and must NOT skip on the VOIDED flag (that flag reflects intent, not
 * completion — skipping would leave the authorization hold in place forever).
 */
export async function processReportVoid(reportId: string): Promise<void> {
  const report = await prisma.qeeqReport.findUnique({ where: { id: reportId } });
  if (!report) throw new Error(`Report ${reportId} not found.`);
  if (!report.paypalAuthorizationId) return;

  const ok = await voidPayment(report.paypalAuthorizationId);
  if (!ok) {
    if (isProduction) throw new Error(`PayPal void for report ${reportId} failed.`);
    return; // dev: void is best-effort
  }
}

export { isProduction };